version: '2.1'

services:

  processor:
    image: blood-tp
    container_name: blood-tp
    build:
      context: processor/
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - .:/sawtooth-blood-chain
    depends_on:
      - shell
      - validator
    entrypoint: |
      /sawtooth-blood-chain/bin/blood_chain_tp -vv tcp://validator:4004